ecoinitiative/events/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from tugoingewa import urls as tugoingewa_urls
from profiles import urls as profiles_urls
#from initiatives import urls as initiatives_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(tugoingewa_urls, namespace='tugoingewa')),
    path('', include(profiles_urls, namespace='profiles')),
    #path('', include(initiatives_urls, namespace='initiatives')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecoinitiative/profiles/urls.py
from django.urls import path
from .views import ProfileView, UserPostsView, InitiativeDetailView

app_name = 'profiles'

urlpatterns = [
       
        path('user_posts/<str:username>', UserPostsView.as_view(), name='user_posts'),
        path('<int:pk>/', InitiativeDetailView.as_view(), name='initiative_details'),

        path('profile/<str:username>/', ProfileView.as_view(), name='profile'),
]

ecoinitiative/tugoingewa/urls.py
from django.urls import path
from .views import (InitiativesList, InitiativeDetailView, EventDetailView, StoriesView, 
                    StoryDetailView, EventsView, ContactUsPageView, PrivacyPolicyView, SuccessView,
                    TermsView, HomePageView ,AboutView, CreateInitiative, AddStory, UpdateStory, DeleteInitiative,
                    UpdateInitiative)

app_name = 'tugoingewa'

urlpatterns = [
    path('success/', SuccessView.as_view(), name='success'),
    path('events/', EventsView.as_view() , name='events'),
    path('addstory/', AddStory.as_view() , name='addstory'),
    path('update_story/<int:pk>/edit/', UpdateStory.as_view() , name='updatestory'),
    path('details/<int:pk>/', StoryDetailView.as_view(), name='details'),
    path('event_details/<int:pk>/', EventDetailView.as_view(), name='event_details'),
    path('stories/', StoriesView.as_view(), name='stories'),
    path('contact/', ContactUsPageView.as_view(), name='contact'),
    path('policy/', PrivacyPolicyView.as_view(), name='policy'),
    path('terms/', TermsView.as_view(), name='terms'),
    path('about/', AboutView.as_view(), name='about'),
    path('', HomePageView.as_view(), name='home'),
    path('create_initiative/', CreateInitiative.as_view() , name='create_initiative'),
    path('initiatives/', InitiativesList.as_view(), name='initiatives'),
    path('<slug:slug>/', InitiativeDetailView.as_view(), name='initiative_details'),
    path('<int:pk>/', InitiativeDetailView.as_view(), name='initiative_details'),
    path('initiatives/<int:pk>/Update/', UpdateInitiative.as_view(), name='update_initiative'),
    path('initiatives/<int:pk>/delete/', DeleteInitiative.as_view(), name='delete_initiative'),
]

ecoinitiative/profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField
from ckeditor.fields import RichTextField

class Profile(models.Model):
    user = models.OneToOneField(
        User, 
        on_delete = models.CASCADE,
        related_name = 'profile'
    )
    profile_image = ImageField(upload_to='images/profile')
    last_name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    bio = RichTextField()
    proffession = models.CharField(max_length=255)

    def __str__(self):
        return str(self.user.username)
    

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    # create a new profile when a new django user is created
    if created:
        Profile.objects.create(user=instance)

ecoinitiative/profiles/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from django.contrib.auth.models import User
from tugoingewa.models import Initiative

class ProfileView(DetailView):
    http_method_names = ['get']
    model = User
    template_name = 'profiles/user.html'
    context_object_name = 'user'
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context['total_posts'] = Initiative.objects.filter(organiser=user).count
        context['user_posts'] = Initiative.objects.all().filter(organiser=user)
        return context


class UserPostsView(ListView):
    http_method_names = ['get']
    template_name = 'profiles/user_posts.html'
    model = Initiative
    context_object_name = 'initiatives'
    slug_field = 'organiser'
    slug_url_kwarg = 'organiser'
    queryset = Initiative.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['initiatives'] = Initiative.objects.all().order_by('-id')
        return context

class InitiativeDetailView(DetailView):
    http_method_names = ['get']
    model = Initiative
    template_name = "initiatives/initiative_details.html"
    context_object_name = 'initiative'

ecoinitiative/templates/profiles/create_profile.html
{% extends 'base.html' %}

{% block title %}
    Create Profile
{% endblock title %}


{% block body %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
    </form>
{% endblock body %}
    
    

ecoinitiative/templates/profiles/user.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
User Profile
{% endblock title %}


{% block link %}
<link rel="stylesheet" href="../../static/guest_user/css/profile.css">
{% endblock link %}


{% load static %}
{% block body %}


<div class="page-content page-container" id="pagecontent">
	<div class="padding">
		<div class="row container d-flex justify-content-center">

			<div class="col-md-8">
				<div class="card p-3 py-4">

					<div class="text-center" id="profile_image">
						<!-- <img src="{{ user.profile.profile_image.url }}" alt="" class="rounded-circle"> -->
					</div>

					<div class="text-center mt-2">
						<h4 class="my-3 mb-0">
							{{user.profile.last_name}} {{ user.profile.surname }}
						</h4>
						<span>
							{{ user.username }}
						</span>
						<h5 class="mt-2">
							{{ user.profile.proffession }}
						</h5>

						<h5 class="mt-2">
							<span style="color: #71c55d;">{{ total_posts }} </span> Initiatives Created 
						</h5>

						<div class="px-4 mt-1">
							<p class="fonts">
								{{ user.profile.bio|safe }}
							</p>
						</div>

						<ul class="social-list">
							<li>
								<a href="#"><i class="bi bi-facebook"></i></a>
							</li>
							<li>
								<a href="#"><i class="bi bi-instagram"></i></a>
							</li>
							<li>
								<a href="#"><i class="bi bi-twitter"></i></a>
							</li>
							<li>
								<a href="#"><i class="bi bi-linkedin"></i></a>
							</li>
							<li>
								<a href="#"><i class="bi bi-google"></i></a>
							</li>
						</ul>

						<div class="buttons">

							{% if request.user.is_authenticated %}
							<a href="#" class="edit btn btn-default px-4 ms-3">
								Edit Profile
							</a>
							{% endif %}

						</div>

					</div>
				</div>
			</div>

		</div>
	</div>
	
</div>

{% endblock body %}

ecoinitiative/templates/profiles/user_posts.html
{% extends 'base.html' %}

{% block body %}

<section class="section-sm" id="post">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 mx-auto"> 


				{% for initiative in initiatives %}
				
				{% if initiative %}
					<article class="card mb-4">

					<div class="post-slider">
						<a href="{% url 'profiles:initiative_details' initiative.pk %}">
							<img src="{{ initiative.initiative_image.url }}" class="card-img-top" alt="post-thumb">
						</a>
					</div>

					<div class="card-body">
						<h3 class="mb-3"><a class="post-title" href="#">{{ initiative.title }}</a></h3>
						<ul class="card-meta list-inline">
							<li class="list-inline-item">
								<a href="{% url 'profiles:initiative_details' initiative.pk %}"
									class="card-meta-event">
									<img src="{{ initiative.organiser.profile.profile_image }}">
									<span>{{ initiative.organiser }}</span>
								</a>
							</li>
							<li class="list-inline-item">
								<i class="ti-timer"></i>{{ initiative.date_created }}
							</li>
							<li class="list-inline-item">
								<ul class="card-meta-tag list-inline">
									<li class="list-inline-item"><a href="tags.html">Ecology</a></li>
									<li class="list-inline-item"><a href="tags.html"></a>Environment</li>
									<li class="list-inline-item"><a href="tags.html">Susainability</a></li>
								</ul>
							</li>
						</ul>
						<p>{{ initiative.description|safe|slice:':200' }}/p>
							<a href="{% url 'profiles:initiative_details' initiative.pk %}"
								class="btn btn-outline-primary">View Details</a>
					</div>
				</article>

				{% else %}
				<h3>
					No Initiatives Created Yet
					<a href="{% url 'tugoingewa:create_initiative' %}" class="btn btn-default">Create One Here</a>
				</h3>
				{% endif %}
					
				
				{% endfor %}

			</div>
		</div>
	</div>
</section>

{% include 'Include/footer.html' %}

{% endblock body %}