ecoinitiative/events/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from tugoingewa import urls as tugoingewa_urls
from profiles import urls as profiles_urls
#from initiatives import urls as initiatives_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(tugoingewa_urls, namespace='tugoingewa')),
    path('', include(profiles_urls, namespace='profiles')),
    #path('', include(initiatives_urls, namespace='initiatives')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecoinitiative/profiles/urls.py
from django.urls import path
from .views import ProfileView, UserPostsView, InitiativeDetailView

app_name = 'profiles'

urlpatterns = [
       
        path('user_posts/<str:username>', UserPostsView.as_view(), name='user_posts'),
        path('<int:pk>/', InitiativeDetailView.as_view(), name='initiative_details'),

        path('profile/<str:username>/', ProfileView.as_view(), name='profile'),
]

ecoinitiative/tugoingewa/urls.py
from django.urls import path
from .views import (InitiativesList, InitiativeDetailView, EventDetailView, StoriesView, 
                    StoryDetailView, EventsView, ContactUsPageView, PrivacyPolicyView, SuccessView,
                    TermsView, HomePageView ,AboutView, CreateInitiative, AddStory, UpdateStory, DeleteInitiative,
                    UpdateInitiative)

app_name = 'tugoingewa'

urlpatterns = [
    path('success/', SuccessView.as_view(), name='success'),
    path('events/', EventsView.as_view() , name='events'),
    path('addstory/', AddStory.as_view() , name='addstory'),
    path('update_story/<int:pk>/edit/', UpdateStory.as_view() , name='updatestory'),
    path('details/<int:pk>/', StoryDetailView.as_view(), name='details'),
    path('event_details/<int:pk>/', EventDetailView.as_view(), name='event_details'),
    path('stories/', StoriesView.as_view(), name='stories'),
    path('contact/', ContactUsPageView.as_view(), name='contact'),
    path('policy/', PrivacyPolicyView.as_view(), name='policy'),
    path('terms/', TermsView.as_view(), name='terms'),
    path('about/', AboutView.as_view(), name='about'),
    path('', HomePageView.as_view(), name='home'),
    path('create_initiative/', CreateInitiative.as_view() , name='create_initiative'),
    path('initiatives/', InitiativesList.as_view(), name='initiatives'),
    path('<slug:slug>/', InitiativeDetailView.as_view(), name='initiative_details'),
    path('<int:pk>/', InitiativeDetailView.as_view(), name='initiative_details'),
    path('initiatives/<int:pk>/Update/', UpdateInitiative.as_view(), name='update_initiative'),
    path('initiatives/<int:pk>/delete/', DeleteInitiative.as_view(), name='delete_initiative'),
]

ecoinitiative/templates/Include/articles.html
{% load thumbnail %}

<div class="col-md-6 mb-4">
    <article class="card article-card article-card-sm h-100">
        <a href="{% url 'tugoingewa:details' story.pk %}">
            <div class="card-image">
                <div class="post-info">
                    <span class="text-uppercase">{{ story.date_created }}</span>
                    <span class="text-uppercase">{{ story.readtime }}</span>
                </div>
                {% thumbnail story.story_image "400x400" crop="center" as im %}
                <img src="{{im.url }}" alt="{{ story.author }}" width="{{ im.width }}" height="{{ im.width }}">
                {% endthumbnail %}
            </div>
        </a>
        <div class="card-body px-0 pb-0">
            <ul class="post-meta mb-2">
                <li> <a href="#!">Ecology</a>
                </li>
            </ul>
            <h2><a class="post-title" href="{% url 'tugoingewa:details' story.pk %}">{{ story.title }}</a></h2>
            <p class="card-text">{{ story.Story|safe|slice:":130" }} ...</p>
            <div class="content"> <a class="read-more-btn" href="{% url 'tugoingewa:details' story.pk %}">Read Full
                    Story</a>
            </div>
        </div>
    </article>
</div>

ecoinitiative/templates/Include/footer.html
  <!-- ======= Footer ======= -->
  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-4">
          <div class="footer-logo">
            <a class="navbar-brand" href="#">Eco Initiative</a>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
              industry's standard dummy text ever since the.</p>
          </div>
        </div>

        <div class="col-sm-6 col-md-3 col-lg-2">
          <div class="list-menu">

            <h4>About Us</h4>

            <ul class="list-unstyled">
              <li><a href="#">About us</a></li>
              <li><a href="#">Features</a></li>
              <li><a href="#">Terms & Conditions</a></li>
              <li><a href="#">Privacy Policy</a></li>
            </ul>

          </div>
        </div>

        <div class="col-sm-6 col-md-3 col-lg-2">
          <div class="list-menu">

            <h4>Quick Links</h4>

            <ul class="list-unstyled">
              <li><a href="#">Initiatives</a></li>
              <li><a href="#">Events</a></li>
              <li><a href="#">stories</a></li>
              <li><a href="#">Privacy Policy</a></li>
            </ul>

          </div>
        </div>

        <div class="col-sm-6 col-md-3 col-lg-2">
          <div class="list-menu">

            <h4>Support</h4>

            <ul class="list-unstyled">
              <li><a href="#">FAQs</a></li>
              <li><a href="#">Contact us</a></li>
              <li><a href="#">Privacy Policy</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6 col-md-3 col-lg-2">
          <div class="list-menu">

            <h4>Our Socials</h4>

            <ul class="list-unstyled d-flex">
              <li class="mx-2"><a href="#"><i class="bi bi-facebook h2"></i></a></li>
              <li class="mx-2"><a href="#"><i class="bi bi-twitter h2"></i></a></li>
              <li class="mx-2"><a href="#"><i class="bi bi-instagram h2"></i></a></li>
              <li class="mx-2"><a href="#"><i class="bi bi-linkedin h2"></i></a></li>
            </ul>

          </div>
        </div>
      </div>
    </div>
    <div class="copyrights">
      <div class="container">
        <p>&copy; Copyrights EcoInitiative Hub. All rights reserved.</p>
      </div>
    </div>
  </footer><!-- End  Footer -->

ecoinitiative/templates/Include/initiatives_list.html
{% load thumbnail %}

<div class="col-lg-6 col-md-6 mb-4">
    <article class="card article-card article-card-sm h-100">
        <a href="{% url 'tugoingewa:initiative_details' initiative.slug %}">
            <div class="card-image">
                <div class="post-info">
                    <span class="text-uppercase">{{ initiative.start_date}}</span>
                    <span class="text-uppercase">{{ initiative.end_date }}</span>
                </div>
                {% thumbnail initiative.initiative_image "400x400" crop="center" as im %}
                <img src="{{im.url }}" alt="{{ initiative.author }}" width="{{ im.width }}" height="{{ im.width }}">
                {% endthumbnail %}
            </div>
        </a>
        <div class="card-body px-0 pb-0">
            <ul class="post-meta mb-2">
                <li> <a href="#!">Ecology</a>
                </li>
            </ul>
            <h2><a class="post-title" href="{% url 'tugoingewa:initiative_details' initiative.slug %}">{{ initiative.title }}</a></h2>
            <p class="card-text">{{ initiative.description|safe|slice:":130" }} ...</p>
            <div class="content"> <a class="read-more-btn" href="{% url 'tugoingewa:initiative_details' initiative.slug %}">View
                    initiative Details</a>
            </div>
        </div>
    </article>
</div>

ecoinitiative/templates/Include/stories_aside.html
<div class="col-lg-12 col-md-6">
    <div class="widget">
        <h2 class="section-title mb-3">Categories</h2>
        <div class="widget-body">
            <ul class="widget-list">
                <li><a href="#!">computer<span class="ml-auto">(3)</span></a>
                </li>
                <li><a href="#!">cruises<span class="ml-auto">(2)</span></a>
                </li>
                <li><a href="#!">destination<span class="ml-auto">(1)</span></a>
                </li>
                <li><a href="#!">internet<span class="ml-auto">(4)</span></a>
                </li>
                <li><a href="#!">lifestyle<span class="ml-auto">(2)</span></a>
                </li>
                <li><a href="#!">news<span class="ml-auto">(5)</span></a>
                </li>
                <li><a href="#!">telephone<span class="ml-auto">(1)</span></a>
                </li>
                <li><a href="#!">tips<span class="ml-auto">(1)</span></a>
                </li>
                <li><a href="#!">travel<span class="ml-auto">(3)</span></a>
                </li>
                <li><a href="#!">website<span class="ml-auto">(4)</span></a>
                </li>
                <li><a href="#!">hugo<span class="ml-auto">(2)</span></a>
                </li>
            </ul>
        </div>
    </div>
</div>