ecoinitiative/events/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from tugoingewa import urls as tugoingewa_urls
from profiles import urls as profiles_urls
#from initiatives import urls as initiatives_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(tugoingewa_urls, namespace='tugoingewa')),
    path('', include(profiles_urls, namespace='profiles')),
    #path('', include(initiatives_urls, namespace='initiatives')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecoinitiative/profiles/urls.py
from django.urls import path
from .views import ProfileView, UserPostsView, InitiativeDetailView

app_name = 'profiles'

urlpatterns = [
       
        path('user_posts/<str:username>', UserPostsView.as_view(), name='user_posts'),
        path('<int:pk>/', InitiativeDetailView.as_view(), name='initiative_details'),

        path('profile/<str:username>/', ProfileView.as_view(), name='profile'),
]

ecoinitiative/tugoingewa/urls.py
from django.urls import path
from .views import (InitiativesList, InitiativeDetailView, EventDetailView, StoriesView, 
                    StoryDetailView, EventsView, ContactUsPageView, PrivacyPolicyView, SuccessView,
                    TermsView, HomePageView ,AboutView, CreateInitiative, AddStory, UpdateStory, DeleteInitiative,
                    UpdateInitiative)

app_name = 'tugoingewa'

urlpatterns = [
    path('success/', SuccessView.as_view(), name='success'),
    path('events/', EventsView.as_view() , name='events'),
    path('addstory/', AddStory.as_view() , name='addstory'),
    path('update_story/<int:pk>/edit/', UpdateStory.as_view() , name='updatestory'),
    path('details/<int:pk>/', StoryDetailView.as_view(), name='details'),
    path('event_details/<int:pk>/', EventDetailView.as_view(), name='event_details'),
    path('stories/', StoriesView.as_view(), name='stories'),
    path('contact/', ContactUsPageView.as_view(), name='contact'),
    path('policy/', PrivacyPolicyView.as_view(), name='policy'),
    path('terms/', TermsView.as_view(), name='terms'),
    path('about/', AboutView.as_view(), name='about'),
    path('', HomePageView.as_view(), name='home'),
    path('create_initiative/', CreateInitiative.as_view() , name='create_initiative'),
    path('initiatives/', InitiativesList.as_view(), name='initiatives'),
    path('<slug:slug>/', InitiativeDetailView.as_view(), name='initiative_details'),
    path('<int:pk>/', InitiativeDetailView.as_view(), name='initiative_details'),
    path('initiatives/<int:pk>/Update/', UpdateInitiative.as_view(), name='update_initiative'),
    path('initiatives/<int:pk>/delete/', DeleteInitiative.as_view(), name='delete_initiative'),
]

ecoinitiative/templates/views.py
from typing import Any
from django import http
from django.http import HttpResponse
from django.views.generic import TemplateView, DetailView, FormView, ListView
from .models import Event
from .forms import AddEventForm
from django.contrib import messages


class IndexPageView(ListView):
    http_method_names = ['get']
    template_name = "index.html"
    model = Event
    context_object_name = 'events'
    queryset = Event.objects.all().order_by('-id')[0:10]

# class HomePageView(ListView):
#     http_method_names = ['get']
#     template_name = 'home.html'
#     model = Event
#     context_object_name = 'events'
#     queryset = Event.objects.all().order_by('-id')[0:4]

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['events'] = Event.objects.all().order_by('-id')[0:4]
    #     return context
       

class EventDetailView(DetailView):
    model = Event
    template_name = "event_details.html"
    

class AddEventView(FormView):
    form_class = AddEventForm
    template_name = "add_event.html"
    success_url = "/"

    
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # create a new form

        new_object = Event.objects.create(
            title = form.cleaned_data['title'],
            event_image = form.cleaned_data['event_image'],
            event_date = form.cleaned_data['event_date'],
            start_time = form.cleaned_data['start_time'],
            end_time = form.cleaned_data['end_time'],
            price = form.cleaned_data['price'],
            location = form.cleaned_data['location'],
            description = form.cleaned_data['description'],
        )
        
        messages.add_message(self.request, messages.SUCCESS, 'Your Event Has Been Successfully Created')
        return super().form_valid(form)
    

class ContactUsPageView(TemplateView):
    template_name = "contact_us.html"

ecoinitiative/templates/addstory.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Create Initiative
{% endblock title %}

{% block body %}

  <section class="section-sm mt-5">
    <div class="container">
      <div class="row mt-5">
        <div class="col-lg-8 mx-auto mt-5">
          
          <div class="content my-5">
            <h2 id="we-would-love-to-hear-from-you">Add An Initiative&hellip;.</h2>
            <p>Initiatives that are Created Successfully will be Public Upon Upload</p>
          </div>
          
          <form method="POST" action="{% url 'tugoingewa:addstory' %}" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <button type="submit" class="btn btn-default btn-lg btn-warning">Create Story</button>
          </form>
        
          </form>
        </div>
      </div>
    </div>
  </section>

{% endblock body %}

ecoinitiative/templates/base.html
{% load static %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="Environment website">

  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Roboto:100,300,400,500,700|Philosopher:400,400i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'guest_user/index/plugins/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'guest_user/index/plugins/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <script defer src="{% static 'guest_user/index/js/waypoint.js' %}"></script>
  <script defer src="{% static 'guest_user/index/js/infinite.js' %}"></script>

  <!-- CDN links -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
    integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

  <!-- Main CSS File -->
  <link href="{% static 'guest_user/css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'guest_user/css/stories.css' %}">


  {% block link %}
  {% endblock link %}


  <title>Tugoingewa | {% block title %} {% endblock title %}</title>
</head>

<body>

  {% if messages %}
  <ul class="messages">

    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}

  </ul>
  {% endif %}

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top">
    <div class="container d-flex align-items-center justify-content-between">

      <div id="logo">
        <h1><a href="{% url 'tugoingewa:home' %}"><span>Eco</span> Initiative</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" title="" /></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="/">Home</a></li>
          <li><a class="nav-link" href="{% url 'tugoingewa:about' %}">About</a></li>
          <li><a class="nav-link" href="{% url 'tugoingewa:initiatives' %}">Initiatives</a></li>
          <li><a class="nav-link" href="{% url 'tugoingewa:events' %}">Events</a></li>
          <li><a class="nav-link" href="{% url 'tugoingewa:stories' %}">Journal</a></li>
          <li><a class="nav-link" href="{% url 'tugoingewa:contact' %}">Contact</a></li>
          {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">

              {% thumbnail user.profile.profile_image "50x50" crop="center" as im %}
              <img class="rounded-circle" src="{{im.url }}" alt="{{ user.username }}" width="{{ im.width }}" height="{{ im.height }}">
              {% endthumbnail %}

              <i class="bi bi-chevron-down ml-1"></i>
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'profiles:profile' user.username %}">Profile</a>
              <a class="dropdown-item" href="{% url 'profiles:user_posts' user.username %}">My Initiatives</a>
              <a class="dropdown-item" href="{% url 'tugoingewa:initiatives' %}">My Stories</a>
              <a class="dropdown-item btn btn-warning my-2" href="{% url 'account_logout' %}">Logout</a>
            </div>
          </li>
          {% else %}
          <li><a class="nav-link ms-4" href="{% url 'account_login' %}">Login / SignUp </a></li>
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  {% block body %}

  {% endblock body %}


  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <!-- JS Plugins -->
  <script src="{% static 'guest_user/index/plugins/jQuery/jquery.min.js' %}"></script>
  <script src="{% static 'guest_user/index/plugins/bootstrap/bootstrap.min.js' %}"></script>
  <script src="{% static 'guest_user/index/plugins/slick/slick.min.js' %}"></script>

  <script src="{% static 'guest_user/index/plugins/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'guest_user/index/plugins/aos/aos.js' %}"></script>
  <script src="{% static 'guest_user/index/plugins/swiper/swiper-bundle.min.js' %}"></script>

  <!-- Main Script -->
  <script src="{% static 'guest_user/index/js/main.js' %}"></script>
  <!-- <script src="{% static 'guest_user/index/js/script.js' %}"></script> -->
</body>

</html>

ecoinitiative/templates/contact_us.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Contact Us
{% endblock title %}

{% block body %}

  <section class="section-sm py-5 my-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          
          <div class="content mb-5">
            <h1 class="section-title my-5 text-center">
              CONTACT US
            </h1>
            <h2 id="we-would-love-to-hear-from-you">We would Love To Hear From You&hellip;.</h2>
            <p>Send a message using the form below</p>
          </div>
          
          <form method="POST" action=".">
            {% csrf_token %}
            <div class="form-group my-3">
              <label for="name">Your Name (Required)</label>
              <input type="text" name="name" id="name" class="form-control" placeholder="John Doe" required>
            </div>
            <div class="form-group my-3">
              <label for="email">Your Email Address (Required)</label>
              <input type="email" name="email" id="email" class="form-control" placeholder="johndoe@gmail.com" required>
            </div>
            <div class="form-group my-3">
              <label for="email">Reason For Contact</label>
              <input type="email" name="email" id="email" class="form-control" placeholder="Inquiry">
            </div>
            <div class="form-group my-3">
              <label for="message">Your Message Here</label>
              <textarea name="message" id="message" class="form-control" placeholder="Lorem ipsum dolor sit amet..."></textarea>
            </div>
            <button type="submit" class="btn btn-lg btn-warning my-3">Send Now</button>
          </form>
        </div>
      </div>
    </div>
  </section>

  {% include 'Include/footer.html' %}

{% endblock body %}

ecoinitiative/templates/events.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}


{% block body %}

<div class="events-header events-bg">
    <div class="container">
        <div class="events-hero">
            <div class="hero-text">
                <h2 class="mb-3"  style="color: #71c55d;">OUR EVENTS</h2>
                <p  style="color: whitesmoke;">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab quo aliquam veniam earum recusandae hic,
                    atque architecto reprehenderit expedita aut!
                </p>
            </div>
        </div>
    </div>
</div>

<!-- main events Section -->

<section class="section-sm">
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-lg-12">

                <div class="top d-flex mt-5">
                    <h2 class="section-title">Upcoming Events</h2>
                </div>
            </div>

            <hr>

            {% for event in events %}

            <div class="col-lg-12 card event_card my-5">
                <div class="row gx-5">
                    <div class="col-md-1 col-4" id="event_date">
                        <h2>{{ event.event_date|date:'d M, Y' }}</h2>
                    </div>
                    <div class="col-md-6">
                        {% thumbnail event.event_image "600x300" crop="center" as im %}
                        <img src="{{im.url }}" alt="{{ event.author }}" width="{{ im.width }}" height="{{ im.height }}">
                        {% endthumbnail %}
                    </div>
                    <div class="col-md-6">
                        <h2 class="title mb-3">{{ event.title }}</h2>
                        <p class="deatz">{{ event.location }} <br> {{ event.start_time }} - {{ event.end_time }} </p>
                        <p class="description">
                            {{ event.description|safe|slice:":285" }} ...
                        </p>
                        <hr>
                        <a class="btn" href="{% url 'tugoingewa:event_details' event.id %}">View Event Details</a>
                    </div>
                </div>
            </div>
            <hr>

            {% endfor %}

            <div class="col-12">
                <div class="row">
                    <div class="col-12">
                        <nav class="mt-4">
                            <!-- pagination -->
                            <nav class="mb-md-50">
                                <ul class="pagination justify-content-center">
                                    <li class="page-item">
                                        <a class="page-link" href="#!" aria-label="Pagination Arrow">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26"
                                                fill="currentColor" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd"
                                                    d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z" />
                                            </svg>
                                        </a>
                                    </li>
                                    <li class="page-item active "> <a href="index.html" class="page-link">
                                            1
                                        </a>
                                    </li>
                                    <li class="page-item"> <a href="#!" class="page-link">
                                            2
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="#!" aria-label="Pagination Arrow">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26"
                                                fill="currentColor" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd"
                                                    d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z" />
                                            </svg>
                                        </a>
                                    </li>
                                </ul>
                            </nav>

                            {% if is_paginated %}
                            {% if page_obj.has_previous %}
                            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                            <a class="btn btn-outline-info mb-4" href="{{ page_obj.previous_page_number}}">Previous</a>
                            {% endif %}
                            {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                            <a class="btn btn-info mb-4" href=" ?page={{ num }}">{{ num }}</a>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <a
                                class="btn btn-outline-info mb-4" href=" ?page={{ num }}">{{ num }}</a>
                                {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                <a class="btn btn-outline-info mb-4"
                                    href="?page={{ page_obj.next_page_number }}">Next</a>
                                <a class="btn btn-outline-info mb-4" href="{{ page_obj.paginator.num_pages }}">Last</a>
                                {% endif %}
                                {% endif %}

                        </nav>
                    </div>
                </div>
            </div>

        </div>
    </div>
    </div>
</section>
{% include 'Include/footer.html' %}

{% endblock body %}

ecoinitiative/templates/stories.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{%block title%} Stories {% endblock %}
{% block body %}

<div class="events-header stories-bg">
    <div class="container">
        <div class="events-hero">
            <div class="hero-text">
                <h2 class="mb-3"  style="color: #71c55d;">STORIES & ARTICLES</h2>
                <p  style="color: whitesmoke;">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab quo aliquam veniam earum recusandae hic,
                    atque architecto reprehenderit expedita aut!
                </p>
            </div>
        </div>
    </div>
</div>

<main>
    <section class="section">
        <div class="container">
            <div class="row no-gutters-lg">
                <div class="col-12 mt-5 d-flex">
                    <h2 class="section-title mt-5">Our Latest Stories & Articles</h2>
                    <a href="{% url 'tugoingewa:addstory' %}" class="lead ms-auto">ADD STORY</a>
                </div>
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="row">

                        {% for story in stories %}
                        {% if forloop.first %}
                        <div class="col-12 mb-4">
                            <article class="card article-card">
                                <a href="{% url 'tugoingewa:details' story.pk %}">
                                    <div class="card-image">
                                        <div class="post-info">
                                            <span class="text-uppercase">{{ story.date_created }}</span>
                                            <span class="text-uppercase">{{ story.readtime }}</span>
                                        </div>
                                        {% thumbnail story.story_image "1000x500" crop="center" as im %}
                                        <img src="{{im.url }}" alt="{{ story.author }}" width="{{ im.width }}"
                                            height="{{ im.height }}">
                                        {% endthumbnail %}
                                        <!-- <img loading="lazy" decoding="async" src="{{ story.story_image.url }}"
                                            alt="Post Thumbnail" class="w-100"> -->
                                    </div>
                                </a>
                                <div class="card-body px-0 pb-1">
                                    <ul class="post-meta mb-2">
                                        <li> <a href="#!">Ecology</a>
                                            <a href="#!">Nature</a>
                                        </li>
                                    </ul>
                                    <h2 class="h1"><a class="post-title"
                                            href="{% url 'tugoingewa:details' story.pk %}">{{ story.title|upper }}</a>
                                    </h2>
                                    <p class="card-text">{{ story.Story|safe|slice:":200" }} ...</p>
                                    <div class="content"> <a class="read-more-btn"
                                            href="{% url 'tugoingewa:details' story.pk %}">Read Full
                                            Article</a>
                                    </div>
                                </div>
                            </article>
                        </div>
                        {% else %}
                        {% include 'Include/articles.html' %}
                        {% endif %}

                        {% endfor %}

                        <div class="col-12">
                            <div class="row">
                                <div class="col-12">
                                    <nav class="mt-4">
                                        <!-- pagination -->
                                        <nav class="mb-md-50">
                                            <ul class="pagination justify-content-center">
                                                <li class="page-item">
                                                    <a class="page-link" href="#!" aria-label="Pagination Arrow">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26"
                                                            fill="currentColor" viewBox="0 0 16 16">
                                                            <path fill-rule="evenodd"
                                                                d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z" />
                                                        </svg>
                                                    </a>
                                                </li>
                                                <li class="page-item active "> <a href="index.html" class="page-link">
                                                        1
                                                    </a>
                                                </li>
                                                <li class="page-item"> <a href="#!" class="page-link">
                                                        2
                                                    </a>
                                                </li>
                                                <li class="page-item">
                                                    <a class="page-link" href="#!" aria-label="Pagination Arrow">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26"
                                                            fill="currentColor" viewBox="0 0 16 16">
                                                            <path fill-rule="evenodd"
                                                                d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z" />
                                                        </svg>
                                                    </a>
                                                </li>
                                            </ul>
                                        </nav>

                                        {% if is_paginated %}
                                        {% if page_obj.has_previous %}
                                        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                                        <a class="btn btn-outline-info mb-4"
                                            href="{{ page_obj.previous_page_number}}">Previous</a>
                                        {% endif %}
                                        {% for num in page_obj.paginator.page_range %}
                                        {% if page_obj.number == num %}
                                        <a class="btn btn-info mb-4" href=" ?page={{ num }}">{{ num }}</a>
                                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <a
                                            class="btn btn-outline-info mb-4" href=" ?page={{ num }}">{{ num }}</a>
                                            {% endif %}
                                            {% endfor %}
                                            {% if page_obj.has_next %}
                                            <a class="btn btn-outline-info mb-4"
                                                href="?page={{ page_obj.next_page_number }}">Next</a>
                                            <a class="btn btn-outline-info mb-4"
                                                href="{{ page_obj.paginator.num_pages }}">Last</a>
                                            {% endif %}
                                            {% endif %}

                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="widget-blocks">
                        <div class="row">
                            <div class="col-lg-12 col-md-6">
                                <div class="widget">
                                    <h2 class="section-title mb-3">Recommended</h2>
                                    <div class="widget-body">
                                        <div class="widget-list">

                                            {% for story in recommended %}

                                            {% if forloop.first %}
                                            <article class="card mb-4">
                                                <div class="card-image">
                                                    <div class="post-info">
                                                        <span class="text-uppercase">{{ story.readtime }}</span>
                                                    </div>
                                                    <img loading="lazy" decoding="async"
                                                        src="{{ story.story_image.url }}" alt="Post Thumbnail"
                                                        class="w-100">
                                                </div>
                                                <div class="card-body px-0 pb-1">
                                                    <h3><a class="post-title post-title-sm" href="{% url 'tugoingewa:details' story.pk %}">
                                                            {{ story.title }}</a></h3>
                                                    <p class="card-text">{{ story.Story|safe|slice:":55" }} ...</p>
                                                    <div class="content"> <a class="read-more-btn"
                                                            href="{% url 'tugoingewa:details' story.pk %}">Read Full Story</a>
                                                    </div>
                                                </div>
                                            </article>
                                            {% else %}
                                            <a class="media d-flex align-items-center" href="{% url 'tugoingewa:details' story.pk %}">
                                                <img loading="lazy" decoding="async" src="{{ story.story_image.url }}"
                                                    alt="Post Thumbnail" class="w-100">
                                                <div class="media-body ms-3">
                                                    <h3 style="margin-top:-5px">{{ story.title }}</h3>
                                                    <p class="mb-0 small">{{ story.Story|safe|slice:":55" }} ...</p>
                                                </div>
                                            </a>
                                            {% endif %}

                                            {% endfor %}

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock body %}